### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by Jesper-Andersson** [stashymane/extra-sounds#32]
Minecraft: 1.18
Mod: 2.2.0 + 2.1.1 + 2.0.2

## Details
Wanted to add the mod to my modpack but sadly makes it totally unplayable.
Loading into a singleplayer world with the mod added makes me unable to enter any singleplayer world.

> Please run the game with `-Dextrasounds.debug=true` added to your Java arguments and attach a log file as well.

Done

![image](https://user-images.githubusercontent.com/5511771/147888415-f053efdf-1b25-4770-8b9c-cd3066941d26.png)

[latest.log](https://github.com/stashymane/extra-sounds/files/7799726/latest.log)

**Comment by stashymane** [comment]
Can you send a link to your modpack please? Would be easier to test on my end

**Comment by Jesper-Andersson** [comment]
It's kinda scuffed so it crashes the first time you try to start it lol
Big fan of the mod so I very much appreciate you taking a look!

https://drive.google.com/file/d/1szZC7FA5FwnboV4PeLxaKBvsKht96AbY/view?usp=sharing

**Comment by stashymane** [comment]
[Seems like this is a known Fabric issue](https://github.com/FabricMC/fabric/issues/410), with enough entries in any registry the Fabric registry sync exceeds the maximum packet size. Since ExtraSounds adds about a thousand new sound events just with vanilla items, reaching the limit is much easier with it installed. This issue isn't specific to ExtraSounds though, nor mods in general - too much of any content will go over the ~2MB packet size limit, [as in this issue relating to recipes](https://bugs.mojang.com/browse/MC-185901). (the sounds.json generated with your modpack is 1MB already)
To work around this, you can try adding the [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) mod, which fixes the issue on my side. Fabric devs have also made [a workaround for the registry sync system](https://github.com/FabricMC/fabric/commit/befed49ea396024c1fd2afbff7df6973052aa00a) by compressing packets. This was committed ~2 hours ago (how convenient!), so the next Fabric API version should fix the crash as well.
Not much I can do about the registry sync system apart from bypassing it - I can't think of any clean way to do this, so I'm closing this issue for now. Once a Fabric API version with the fix is released, I'm going to set that as the minimum API version.

**Comment by stashymane** [comment]
[Fabric API 0.45.1](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3591502) fixed this :)
